version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.20.8@sha256:b4cda63ce8c33c7a4795cd4253f2bc907703381d9bbf4ae78de7e75ca743560f
    working_directory: ~/pix-captain-test
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - v1-api-npm-{{ checksum "cachekey" }}
      - run: npm ci
      - save_cache:
          key: v1-api-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - run:
          name: Run test
          command: npm run test