name: Merge on Dev
on:
  push:
    branches:
      - main
jobs:
  call-on-pix-dev-merge-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call on pix dev merge action
        id: pix-on-dev-merge-action
        uses: 1024pix/pix-on-dev-merge-action@v1.0.0
        with:
          GITHUB-TOKEN: "${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}"
      - name: Send message to a Pix Team
        uses: slackapi/slack-github-action@v1.14.0
        with:
          channel-id: ${{ steps.pix-on-dev-merge-action.outputs.label }}
          slack-message: 'Le fichier de configuration a été modifié. Vérifier les varaiables d''environnement sur Scalingo Intégration'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.PIX_BOT_RUN_SLACK_TOKEN }}
