name: Merge on Dev
on:
  push:
    branches:
      - main
jobs:
  call-on-pix-dev-merge-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call on pix dev merge action
        id: pix-on-dev-merge-action
        uses: 1024pix/notify-team-on-config-file-change@v1.4.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_BOT_TOKEN: ${{ secrets.PIX_BOT_RUN_SLACK_TOKEN }}
          INTEGRATION_ENV_URL: ${{ secrets.INTEGRATION_ENV_URL }}
