name: Merge on Dev
on:
  push:
    branches:
      - main
jobs:
  call-on-pix-dev-merge-action:
    runs-on: ubuntu-latest
    steps:
      - name: Call on pix dev merge action
        id: pix-on-dev-merge-action
        uses: 1024pix/pix-on-dev-merge-action@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.PIX_BOT_RUN_SLACK_TOKEN }}