name: Merge on Dev
on:
  push:
    branches:
      - main
jobs:
  call-on-pix-dev-merge-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call on pix dev merge action
        uses: 1024pix/pix-on-dev-merge-action@v1.0.0
        with:
          github-token: "${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}"
